repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        verbose: true

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        verbose: true

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
        verbose: true

  - repo: local
    hooks:
      - id: check governance
        name: Run task check governance before push
        entry: task governance
        language: system
        pass_filenames: false
        stages: [pre-push]
        verbose: true
